# Generated by Django 5.2.7 on 2025-11-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personas',
            options={'managed': False},
        ),
    ]
